name: Unpack Whacky Auctions v1
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  unpack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo ready
